services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_node_docker
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: my_db_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - "3306:3306"
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
  
  nginx:
    image: nginx:stable-alpine
    container_name: proxy_reverse    
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
